version: "2"

run:
  timeout: 10m
  tests: true
  go: "1.25"

# =========================
# ===== FORMATTERS =======
# =========================
# Production-safe, idempotent, no conflicts
formatters:
  enable:
    - gofmt
    - goimports

# =========================
# ===== LINTERS ==========
# =========================
linters:
  enable-all: true
  disable:
    # --- noisy / subjective / low value ---
    - wsl
    - godot
    - gomoddirectives
    - mnd
    - nestif
    - nlreturn
    - exhaustruct
    - nonamedreturns
    - paralleltest
    - testpackage

# =========================
# ===== LINTER SETTINGS ==
# =========================
linters-settings:

  # ---------- STYLE / DOCS ----------
  revive:
    severity: error
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers"]
      - name: package-comments
      - name: var-naming
      - name: line-length-limit
        arguments: [100]
      - name: unexported-return
      - name: confusing-naming
      - name: early-return
      - name: defer
      - name: modifies-parameter

  stylecheck:
    checks:
      - all

  lll:
    line-length: 100

  whitespace:
    multi-if: true
    multi-func: true

  misspell:
    locale: US

  # ---------- ERRORS ----------
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true

  wrapcheck:
    strict: true
    ignoreSigs:
      - fmt.Errorf(
      - errors.New(

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  nilnil:
    detect-nil-interface: true

  bodyclose:
    check-defer: true

  # ---------- COMPLEXITY ----------
  gocyclo:
    min-complexity: 3

  cyclop:
    max-complexity: 5

  funlen:
    lines: 30
    statements: 15

  maintidx:
    under: 20

  dupl:
    threshold: 70

  # ---------- PERFORMANCE ----------
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  unparam:
    check-exported: true

  makezero:
    always: true

  # ---------- DEEP ANALYSIS ----------
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
      - experimental
      - security
    disabled-checks:
      - unnamedResult

  govet:
    enable-all: true
    disable:
      - fieldalignment

  staticcheck:
    checks:
      - all

  gosimple: {}
  ineffassign: {}
  unused: {}
  typecheck: {}

  # ---------- SECURITY ----------
  gosec:
    severity: high
    confidence: high

  # ---------- IMPORTS ----------
  gci:
    sections:
      - standard
      - default
      - prefix(ProxyMaster_v2)

  goimports:
    local-prefixes: ProxyMaster_v2

  # ---------- POLICY ----------
  depguard:
    rules:
      Main:
        files:
          - "main.go"
        deny:
          - pkg: "*"
            desc: "main must not import external packages directly"

  varnamelen:
    min-name-length: 4
    max-distance: 5

  exhaustive:
    default-signifies-exhaustive: true

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake

# =========================
# ===== ISSUES ===========
# =========================
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
