version: "2"

run:
  timeout: 10m
  tests: true
  issues-exit-code: 1
  skip-dirs-use-default: false
  allow-parallel-runners: true

output:
  format: colored-line-number
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  fix: false

linters-settings:

  govet:
    enable-all: true
    settings:
      shadow:
        strict: true

  gocyclo:
    min-complexity: 15

  cyclop:
    max-complexity: 15

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 30

  lll:
    line-length: 120
    tab-width: 1

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  whitespace:
    multi-if: true
    multi-func: true

  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    confidence: 0.0
    rules:
      - name: var-naming
      - name: line-length-limit
      - name: function-length
      - name: cognitive-complexity
      - name: deep-exit
      - name: argument-limit
        arguments: [3]
      - name: file-header
      - name: unhandled-error
      - name: bare-return
      - name: early-return
      - name: confusing-results
      - name: superfluous-else
      - name: useless-break
      - name: struct-tag
      - name: unnecessary-stmt

  staticcheck:
    checks: ["all"]

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  nestif:
    min-complexity: 5

  exhaustive:
    default-signifies-exhaustive: true

  wrapcheck:
    ignoreSigs: []
    ignorePackageGlobs: []

  forbidigo:
    forbid:
      - p: ^fmt\.Print.*$
        msg: "Запрещён прямой вывод в stdout"
      - p: ^log\.Print.*$
        msg: "Используй структурированный логгер"

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "errors.Wrap запрещён"

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
        xml: snake
        bson: snake

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    # БАЗА
    - govet
    - errcheck
    - staticcheck
    - revive
    - ineffassign
    - unused

    # СТИЛЬ И ЧИТАЕМОСТЬ
    - nlreturn
    - whitespace
    - lll
    - misspell
    - goconst
    - funlen
    - gocyclo
    - cyclop
    - gocognit
    - nestif
    - dupl

    # БЕЗОПАСНОСТЬ
    - gosec
    - bodyclose
    - noctx

    # АРХИТЕКТУРА
    - forbidigo
    - prealloc
    - exhaustive
    - wrapcheck
    - tagliatelle

    # ПАРАНОЙЯ
    - asciicheck
    - bidichk
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - makezero
    - nilerr
    - nilnil
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - wastedassign
    - nolintlint
